/**
 * Loads the committed dataset.
 *
 * `servers.json` is a build artifact, not a live fetch: the browser cannot
 * build it (CORS blocks both glama.ai and raw.githubusercontent, and GitHub
 * allows only 60 anonymous calls an hour against ~3,000 repos), so the file is
 * generated by `pnpm run build:data` and committed. The upside is that the app
 * is static and works offline.
 */
import { useEffect, useState } from "react";

import type { Server } from "../lib/server.ts";

export type ServersState =
  | { readonly kind: "error"; readonly message: string }
  | { readonly kind: "loading" }
  | { readonly kind: "ready"; readonly servers: readonly Server[] };

export function useServers(url = "servers.json"): ServersState {
  const [state, setState] = useState<ServersState>({ kind: "loading" });

  useEffect(() => {
    let isCancelled = false;

    async function load(): Promise<void> {
      try {
        const response = await fetch(url);
        if (!response.ok) throw new Error(`HTTP ${response.status}`);
        const servers = (await response.json()) as Server[];
        if (!isCancelled) setState({ kind: "ready", servers });
      } catch (error) {
        if (!isCancelled) {
          setState({
            kind: "error",
            message: Error.isError(error) ? error.message : String(error),
          });
        }
      }
    }

    void load();
    return (): void => {
      isCancelled = true;
    };
  }, [url]);

  return state;
}
